[build]
builder = "NIXPACKS"
dir = "backend"

[deploy]
startCommand = "gunicorn -k uvicorn.workers.UvicornWorker genscholar.asgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

